**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd
frame = pd.DataFrame(data)
# Q1
print(frame)
# Q2
print()
print(frame[((frame["job"] == "psychologist") | (frame["job"] == "teacher")) & (frame["num_cars"]> frame["family_size"])])
# Q3
print()
print(frame[(frame["family_size"] <= 2) & (frame["num_cars"] >= 1)])
# Q4
print()
uniquejobs = frame["job"].nunique()
print("Number of unique jobs in this dataset is", uniquejobs)

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

Number of unique jobs in this dataset is 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
data = {"fruit": fruit, "weights":weights}
df = pd.DataFrame(data)
print("Apple:")
print(pd.DataFrame.mean(df.weights[fruit == "apple"]))
print("Banana:")
print(pd.DataFrame.mean(df.weights[fruit == "banana"]))
print("Carrot:")
print(pd.DataFrame.mean(df.weights[fruit == "carrot"]))

Apple:
4.0
Banana:
4.8
Carrot:
9.5


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
#Q1
course_name_sorted = np.sort(course_name)
courseindex=[]
for i in course_name_sorted:
  courseindex.append(np.where(course_name == i))
print(courseindex)
#Q2
check = np.char.startswith(course_name, "P")
print(check)

[(array([1]),), (array([3]),), (array([0]),), (array([2]),), (array([4]),)]
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
#Q1
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("original:", student_id)
id_reversed = student_id[::-1]
print("reversed:", id_reversed)
# Q2
id_sorted = np.sort(id_reversed)
print("The 3-largest values of student id is", id_sorted[-3])

original: [1023 5202 6230 1671 1682 5241 4532]
reversed: [4532 5241 1682 1671 6230 5202 1023]
The 3-largest values of student id is 5202


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
import numpy as np
# Hint: you can use arange to start off
arr1 = np.arange(3,100)
arr2 = arr1[(arr1 % 3 ==0) | (arr1%5 ==0)]
print(np.sum(arr2))

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [ ]:
import numpy as np
arr = np.arange(12).reshape(3,4)
#Q1
print("Original array:\n", arr)
arr[:, [1,2]] = arr[:,[2,1]]
print("Swapped-columns array:\n", arr)
#Q2
arr = np.arange(12).reshape(3,4)
arr[[0,1],:] = arr[[1,0],:]
print("Swapped-rows array:\n", arr)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swapped-columns array:
 [[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
Swapped-rows array:
 [[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
